services:

    engage360d_takeda.twig.takeda_extension:
        class: Engage360d\Bundle\TakedaBundle\Twig\TakedaExtension
        arguments:
          - @engage360d_takeda.geo_ip_resolver
        tags:
          - { name: twig.extension }

    engage360d_page_elastica_transformer:
        class: Engage360d\Bundle\TakedaBundle\PageToElasticaTransformer

    engage360d_takeda.geo_ip_resolver:
        class: Engage360d\Bundle\TakedaBundle\GeoIPResolver
        arguments:
          - @request_stack

    engage360d_takeda.json_api_response:
        class: Engage360d\Bundle\TakedaBundle\Services\JsonApiResponse
        calls:
            - [setContainer, [@service_container]]

    # Listeners/Subscribers

    engage360d_takeda.listener.reset_password:
        class: Engage360d\Bundle\TakedaBundle\Event\ResetPasswordSubscriber
        arguments:
            - @mailer
            - @router
            - @templating
            - @service_container
        tags:
            - { name: kernel.event_subscriber }

#    engage360d_takeda.listener.email_confirmation:
#        class: Engage360d\Bundle\TakedaBundle\Event\EmailConfirmationListener
#        arguments:
#            - @mailer
#            - @fos_user.util.token_generator
#            - @router
#            - @session
#            - @templating
#            - @service_container
#        tags:
#            - { name: kernel.event_subscriber }

    # Forms

    engage360d_takeda.form.user.post:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_takeda_post_user", null, { }]
        tags:
            - { name: rest.form, route: post_users }
            - { name: rest.manager, route: post_users }

    engage360d_takeda.form.security.post.type:
        class: Engage360d\Bundle\TakedaBundle\Form\Type\PostUserFormType
        arguments: [Engage360d\Bundle\TakedaBundle\Entity\User\User]
        tags:
            - { name: form.type, alias: engage360d_takeda_post_user }

    engage360d_takeda.form.user.put:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_takeda_put_user", null, { }]
        tags:
            - { name: rest.form, route: put_users }
            - { name: rest.manager, route: put_users }

    engage360d_takeda.form.security.put.type:
        class: Engage360d\Bundle\TakedaBundle\Form\Type\PutUserFormType
        arguments: [Engage360d\Bundle\TakedaBundle\Entity\User\User]
        tags:
            - { name: form.type, alias: engage360d_takeda_put_user }

    engage360d_takeda.form.registration:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments: ["user", "engage360d_takeda_registration", null, { }]

    engage360d_takeda.form.registration.type:
        class: Engage360d\Bundle\TakedaBundle\Form\Type\RegistrationUserFormType
        arguments: [%engage360d_security.entity.user.class%]
        tags:
            - { name: form.type, alias: engage360d_takeda_registration }

    # Test Results

    engage360d.takeda_test.processing.score_calculator:
        class: Engage360d\Bundle\TakedaBundle\Processing\ScoreCalculator

    engage360d.takeda_test.processing.recommendations_mather:
        class: Engage360d\Bundle\TakedaBundle\Processing\RecommendationsMatcher

    engage360d.takeda_test.processing.recommendations_mather_factory:
        class: Engage360d\Bundle\TakedaBundle\Processing\RecommendationsMatcherFactory
        arguments:
            - @router

    engage360d.takeda_test.processing.test_result_filler:
        class: Engage360d\Bundle\TakedaBundle\Processing\TestResultFiller
        arguments:
            - @engage360d.takeda_test.processing.score_calculator
            - @engage360d.takeda_test.processing.recommendations_mather_factory

    engage360d.takeda_test.processing.test_result_filler_listener:
        class: Engage360d\Bundle\TakedaBundle\Processing\TestResultFillerListener
        arguments:
            - @engage360d.takeda_test.processing.test_result_filler
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    # Bocks

    engage360d_takeda.block.good_to_know:
        class: Engage360d\Bundle\TakedaBundle\Block\GoodToKnow
        arguments:
            - engage360d_takeda.block.good_to_know
            - @templating
        tags:
            - { name: sonata.block }

    engage360d_takeda.block.map:
        class: Engage360d\Bundle\TakedaBundle\Block\Map
        arguments:
            - engage360d_takeda.block.map
            - @templating
        tags:
            - { name: sonata.block }

    # Other

    engage360d_takeda.timeline_manager:
        class: Engage360d\Bundle\TakedaBundle\Services\TimelineManager
        arguments: [ @service_container ]
    engage360d_takeda.reports_manager:
        class: Engage360d\Bundle\TakedaBundle\Services\ReportsManager
        arguments: [ @service_container ]
