# OAuth

engage360d_oauth_redirect_to_service:
  pattern: /oauth/{service}
  defaults:  { _controller: Engage360dTakedaBundle:Security:redirectToService }

hwi_oauth_connect_service:
  pattern: /oauth/service/{service}
  defaults:  { _controller: Engage360dTakedaBundle:Security:connectService }

#engage360d_oauth_connect_registration:
#  pattern: /oauth/registration/{key}
#  defaults:  { _controller: Engage360dSecurityBundle:Security:connectRegistration }

engage360d_oauth_connect_success:
    pattern: /oauth/connect/success
    defaults: { _controller: Engage360dTakedaBundle:Security:connectSuccess }

engage360d_oauth_connect_failure:
    pattern: /oauth/connect/failure
    defaults: { _controller: Engage360dTakedaBundle:Security:connectFailure }

# Other

engage360d_takeda_main_mainpage:
    path: /
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Main:mainpage }

engage360d_takeda_auth_signin:
    path: /sign-in
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Auth:signin }

engage360d_takeda_risk_analysis:
    path: /risk-analysis
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:RiskAnalysis:index }

engage360d_takeda_institutions:
    path: /institutions
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Institutions:institutions }

engage360d_takeda_institution:
    path: /institutions/{id}
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Institutions:institution }

engage360d_takeda_account_recommendations:
    path: /account/recommendations
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Account:recommendations }

engage360d_takeda_account_timeline:
    path: /account/timeline
    defaults: { _controller: Engage360dTakedaBundle:Account:timeline }

engage360d_takeda_account_settings:
    path: /account/settings
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Account:settings }

engage360d_takeda_search:
    path: /search
    defaults: { _controller: Engage360dTakedaBundle:Search:index }

engage360d_takeda_press_center:
    path: /press-center
    defaults: { _controller: Engage360dTakedaBundle:PressCenter:index }

engage360d_takeda_press_center_article:
    path: /press-center/{articleType}/{id}
    defaults: { _controller: Engage360dTakedaBundle:PressCenter:article }

engage360d_takeda_test_get_test_result_recommendation:
    path: /test-results/{id}/{type}
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Test:getTestResultRecommendation }
