engage360d_takeda_main_mainpage:
    path: /
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Main:mainpage }

engage360d_takeda_search_results_page:
    path: /search
    methods: [GET]
    defaults: { _controller: Engage360dTakedaBundle:Search:search }
