imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
#        firephp:
#            type:  firephp
#            level: info
#        chromephp:
#            type:  chromephp
#            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

lexik_jwt_authentication:
    token_ttl: 157680000 # 5 years

# Don't delete NelmioApiDocBundle,
# because some of melodia bundles are dependent on it
nelmio_api_doc: ~

