imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true, enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

sensio_framework_extra:
    view: { annotations: false }

jms_security_extra:
    secure_all_services: false
    expressions: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: %kernel.debug%
    variables:
        locale: [en, ru]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%_%kernel.environment%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

stof_doctrine_extensions:
    orm:
        default:
            sluggable:   true
            softdeleteable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: @Engage360dSecurityBundle/Resources/config/serializer/fos
    property_naming:
        separator:  ~
        lower_case: false

fos_rest:
    param_fetcher_listener: force
    exception: ~
    view:
        view_response_listener: force
        jsonp_handler: ~
        exception_wrapper_handler: Engage360d\Bundle\TakedaBundle\Handler\ExceptionWrapperHandler
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
      rules:
        - { path: '^/api', priorities: ['json'] }
        - { path: '^/', priorities: ['html'] }

fos_oauth_server:
    service:
        user_provider: engage360d_security.manager.user
    db_driver: orm
    client_class:        Engage360d\Bundle\TakedaBundle\Entity\OAuth\Client
    access_token_class:  Engage360d\Bundle\TakedaBundle\Entity\OAuth\AccessToken
    refresh_token_class: Engage360d\Bundle\TakedaBundle\Entity\OAuth\RefreshToken
    auth_code_class:     Engage360d\Bundle\TakedaBundle\Entity\OAuth\AuthCode

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Engage360d\Bundle\TakedaBundle\Entity\User\User

hwi_oauth:
    connect: true
    firewall_name: main
    target_path_parameter: _target_path
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_client_id%"
            client_secret:       "%facebook_client_secret%"
            options:
                display: popup
        vkontakte:
            type:                vkontakte
            client_id:           "%vkontakte_client_id%"
            client_secret:       "%vkontakte_client_secret%"

fos_elastica:
    serializer: ~
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            types:
                page:
                    serializer:
                        groups: [elastica, Default]
                    persistence:
                        driver: orm
                        model: Melodia\PageBundle\Entity\Page
                        provider: ~
                        listener:
                            insert: true
                            update: true
                            delete: true

lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      %ssh_key.passphrase%                    # ssh key pass phrase
    token_ttl:        86400                                   # token ttl - defaults to 86400

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text:
