
# Security routes

facebook_login:
    pattern: /sign-in/facebook

vkontakte_login:
    pattern: /sign-in/vkontakte

engage360d_takeda_logout:
    pattern: /logout

# Api routes

engage360d_search_api:
    resource: "@Engage360dSearchBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

engage360d_takeda_bundle_api:
    resource: "@Engage360dTakedaBundle/Controller/Api"
    type: annotation
    prefix: /api/v1

melodia_pages_api_:
    resource: "@MelodiaPageBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

engage360d_countries_api:
    resource: "@Engage360dCountriesBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

# Other routes

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth

hwi_oauth_connect_service:
  pattern: /oauth/service/{service}
  defaults:  { _controller: Engage360dSecurityBundle:Security:connectService }

hwi_oauth_connect_registration:
  pattern: /oauth/registration/{key}
  defaults:  { _controller: Engage360dSecurityBundle:Security:connectRegistration }

engage360d_takeda:
  resource: "@Engage360dTakedaBundle/Resources/config/routing/routing.yml"

