# Api routes

engage360d_search_api:
    resource: "@Engage360dSearchBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

engage360d_takeda_bundle_api:
    resource: "@Engage360dTakedaBundle/Controller/Api"
    type: annotation
    prefix: /api/v1

engage360d_countries_api:
    resource: "@Engage360dCountriesBundle/Resources/config/routing/api.yml"
    prefix:   /api/v1

engage360d_old_api_pages:
    type:     rest
    resource: Engage360d\Bundle\TakedaBundle\Controller\OldApi\PageController
    prefix: /api/old

# Security routes

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth

facebook_login:
    pattern: /sign-in/facebook

vkontakte_login:
    pattern: /sign-in/vkontakte

google_login:
    pattern: /sign-in/google

odnoklassniki_login:
    pattern: /sign-in/odnoklassniki

engage360d_takeda_sign_out:
    pattern: /sign-out
    defaults:  { _controller: Engage360dTakedaBundle:Account:logout }

# Other routes

engage360d_takeda:
  resource: "@Engage360dTakedaBundle/Resources/config/routing/routing.yml"

engage360d_subscription:
  resource: "@Engage360dSubscriptionBundle/Resources/config/routing/api.yml"
  prefix: /api/v1

melodia_page_wildcard:
    pattern:  /{url}
    defaults: { _controller: Engage360dTakedaBundle:Page:index, url: null }
    requirements:
        url: ".+"