engage360d_search_api:
    resource: "@Engage360dSearchBundle/Resources/config/routing/api.yml"
    prefix:   /api

engage360d_user_api:
    resource: "@Engage360dSecurityBundle/Resources/config/routing/api.yml"
    prefix:   /api

engage360d_pages_api:
    resource: "@Engage360dPagesBundle/Resources/config/routing/api.yml"
    prefix:   /api

engage360d_countries_api:
    resource: "@Engage360dCountriesBundle/Resources/config/routing/api.yml"
    prefix:   /api

engage360d_user_security:
    resource: "@Engage360dSecurityBundle/Resources/config/routing/security.yml"
    prefix:   /user

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

engage360d_takeda:
  resource: "@Engage360dTakedaBundle/Resources/config/routing/routing.yml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /user/connect

facebook_login:
    pattern: /user/login_facebook

engage360d_takeda_user:
  resource: "@Engage360dTakedaUserBundle/Resources/config/routing/routing.yml"

engage360d_takeda_test:
  resource: "@Engage360dTakedaTestBundle/Resources/config/routing/routing.yml"
