jms_security_extra:
    secure_all_services: false
    expressions: true
    #voters: false

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        admin:
            pattern:    ^/admin|^/oauth/v2/auth|^/api
            provider:   fos_userbundle
            fos_oauth:  true
            anonymous:  true
            form_login:
                login_path: /admin.html
                check_path:  /admin/login_check
                default_target_path: /admin/login_success
                provider: fos_userbundle
                use_referer: false
                use_forward: false
                failure_path: /admin.html
                failure_forward: true
                always_use_default_target_path: true
                post_only: true
            logout:
                path:   /admin/logout
                target: /admin.html
                invalidate_session: true

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/oauth/v2/auth, roles: [ IS_AUTHENTICATED_FULLY ] }
