jms_security_extra:
    secure_all_services: false
    expressions: true
    #voters: false

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Melodia\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        admins:
            entity: { class: Melodia\UserBundle\Entity\User , property: username }

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        login:
            pattern:  ^/login|logout|tokens
            stateless: true
            anonymous: ~
            form_login:
                provider: admins
                check_path: melodia_user_get_token
                login_path: melodia_user_check_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            logout:
                path:   /logout
                target: /
        api:
            pattern:    ^/api
            stateless: true
            anonymous: true
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer
                query_parameter:      # check token in query string parameter
                    enabled: true
                    name:    token
                throw_exceptions: false     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point: true

        main:
            pattern: ^/
            anonymous:  true
            fos_oauth:  true
            http_basic: ~
            context: auth
            form_login:
                login_path: engage360d_takeda_user_login
                check_path:  engage360d_takeda_user_login_check
                default_target_path: /account
                provider: fos_userbundle
                use_referer: true
                use_forward: true
                failure_path: engage360d_takeda_user_login_failuer
                failure_forward: true
                post_only: true
                require_previous_session: false
            oauth:
                resource_owners:
                    facebook:      facebook_login
                    vkontakte:     vkontakte_login
                login_path:        /account
                failure_path:      engage360d_security_user_connect
                oauth_user_provider:
                    service: engage360d_security.oauth.provider
            logout:
                path:   /account/logout
                target: /
                invalidate_session: true

    access_control:
        - { path: ^/api/search, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/api/test-results, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/countries, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/api/normal/users/me, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }

        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

        - { path: ^/user/connect, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }

        - { path: ^/oauth/v2/auth, roles: [ IS_AUTHENTICATED_FULLY ] }
