jms_security_extra:
    secure_all_services: false
    expressions: true
    #voters: false

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_DOCTOR: ROLE_USER
        ROLE_ADMIN:  [ROLE_USER, ROLE_DOCTOR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern: ^/api
            anonymous: true
            http_basic: ~
            context: shared_context
            lexik_jwt:
                query_parameter:            # check token in query string parameter
                    enabled: true
                    name:    token
        main:
            pattern: ^/
            anonymous: true
            http_basic: ~
            context: shared_context
            oauth:
                resource_owners:
                    facebook:      facebook_login
                    vkontakte:     vkontakte_login
                login_path:        /sign-in
                failure_path:      engage360d_oauth_connect_failure
                use_forward:       false
                oauth_user_provider:
                    service: engage360d_security.oauth.provider

    access_control:
        - { path: ^/account, roles: [ ROLE_USER ] }

#        # API

        - { path: ^/api/v1/regions, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api/v1/records, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }

        - { path: ^/api/v1/users, roles: [ROLE_ADMIN], methods: [GET] }
        - { path: ^/api/v1/users/\d+/reset-password, roles: [ROLE_ADMIN], methods: [POST] }
        - { path: ^/api/v1/users/\d+, roles: [ROLE_ADMIN], methods: [PUT, DELETE] }
        - { path: ^/api/v1/users, roles: [IS_AUTHENTICATED_ANONYMOUSLY], methods: [POST] }

        # /tokens, /tokens/facebook, /tokens/vk
        - { path: ^/api/v1/tokens, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [POST] }

        - { path: ^/api/v1/account/reset-password$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [POST] }
        - { path: ^/api/v1/account, roles: [ ROLE_USER ] }

        # Press-center
        - { path: ^/api/v1/news, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api/v1/opinions, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
        - { path: ^/api/v1/experts, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }

        - { path: ^/api/v1/institutions, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [GET] }
#
#
#        - { path: ^/api/v1/search, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
#        - { path: ^/api/v1/test-results, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/v1/countries, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
#
#
        - { path: ^/api, roles: [ ROLE_ADMIN ] }

        #- { path: ^/api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
