engage360d_takeda_user_login:
    path:      /user/login
    defaults:  { _controller: Engage360dTakedaUserBundle:User:login }

engage360d_takeda_user_login_check:
    path: /user/check

engage360d_takeda_user_profile:
    path: /user
    defaults: { _controller: Engage360dTakedaUserBundle:User:profile }

engage360d_takeda_user_registration:
    path: /user/registration
    defaults: { _controller: Engage360dTakedaUserBundle:User:registration }

engage360d_takeda_user_registration_confirm:
    path: /account/confirm/{token}
    defaults: { _controller: Engage360dTakedaUserBundle:Account:confirm }

engage360d_takeda_user_reset_password:
    path: /account/reset/{token}
    defaults: { _controller: Engage360dTakedaUserBundle:Account:reset }

engage360d_takeda_user_account:
    path: /account
    defaults: { _controller: Engage360dTakedaUserBundle:Account:account }
