engage360d_takeda_user_login_check:
    path: /account/check

engage360d_takeda_user_registration_confirm:
    path: /account/confirm/{token}
    defaults: { _controller: Engage360dTakedaUserBundle:Account:confirm }

engage360d_takeda_user_reset_password:
    path: /account/reset/{token}
    defaults: { _controller: Engage360dTakedaUserBundle:Account:reset }

engage360d_takeda_user_login_failuer:
    path: /account/failure
    defaults: { _controller: Engage360dTakedaUserBundle:Account:failureLogin }