Engage360d\Bundle\TakedaTestBundle\Entity\TestResult:
  constraints:
    - Callback: [validateSugarProblemsOrDrugs]
  properties:
    sex:
      - NotBlank: ~
      - Choice: { choices: [male, female] }
    birthday:
      - NotBlank: ~
      - Date: ~
    growth:
      - NotBlank: ~
      - Type: { type: integer }
      - Range: { min: 30, max: 300 }
    weight:
      - NotBlank: ~
      - Type: { type: integer }
      - Range: { min: 30, max: 700 }
    smoking:
      - Type: { type: boolean }
    cholesterolLevel:
      - NotBlank: ~
      - Type: { type: integer }
      - Range: { min: 3, max: 9 }
    cholesterolDrugs:
      - Type: { type: boolean }
    diabetes:
      - Type: { type: boolean }
    sugarProblems:
      - Type: { type: boolean }
    sugarDrugs:
      - Type: { type: boolean }
    arterialPressure:
      - NotBlank: ~
      - Type: { type: integer }
      - Range: { min: 80, max: 200 }
    arterialPressureDrugs:
      - Type: { type: boolean }
    physicalActivity:
      - NotBlank: ~
      - Type: { type: integer }
      - Range: { min: 80, max: 200 }
    heartAttackOrStroke:
      - Type: { type: boolean }
    extraSalt:
      - Type: { type: boolean }
    acetylsalicylicDrugs:
      - Type: { type: boolean }
