#%RAML 0.8
title: Cardiomagnyl API
version: v1

baseUri: "{schema}://{domain}/api/{version}"
baseUriParameters:
  schema:
    enum: [ http, https ]
  domain:
    enum: [ cardiomagnyl.iengage.ru, cardiomagnyl.ru ]

securitySchemes:
  - x-query-token:
      type: x-query-token
      describedBy:
        queryParameters:
          token:
            type: string
            example: "ACCESS_TOKEN"
            description: |
              Don't forget to escape token.
        responses:
          401:
            description: |
              Token is invalid or expired.

traits:
  - secured:
      securedBy: [ x-query-token ]
      queryParameters:
        token:
          type: string
          example: "ACCESS_TOKEN"
          description: |
            Don't forget to escape token.

  - admin-only:
      responses:
        403:
          description: |
            `ROLE_ADMIN` is required to perform this operation.

  - paged:
      queryParameters:
        page:
          type: number
          example: 1
          description: |
            Starting from one.
        limit:
          type: number
          example: 10
          description: |
            Page limit.

/users:
  get:
    is: [ secured, admin-only, paged ]
  post:
    description: |
      User registration.
    body:
      application/json:
        schema: !include v1/schemas/users/post.json
        example: !include v1/examples/users/post.json
    responses:
      201:
        body:
          application/json:
            schema: !include v1/schemas/users/one.json
            example: !include v1/examples/users/one.json
  /{id}:
    get:
      is: [ secured, admin-only ]
      responses:
        200:
          body:
            application/json:
              schema: !include v1/schemas/users/one.json
              example: !include v1/examples/users/one.json
    patch:
      is: [ secured, admin-only ]
      body:
        application/json:
          schema: !include v1/schemas/users/patch.json
          example: !include v1/examples/users/patch.json
      responses:
        200:
          body:
            application/json:
              schema: !include v1/schemas/users/one.json
              example: !include v1/examples/users/one.json
    delete:
      is: [ secured, admin-only ]
      responses:
        200:
    /reset-password:
      post:
        is: [ secured, admin-only ]
        responses:
          200:

/account:
  post:
    description: |
      User authentication.
    body:
      application/json:
        schema: !include v1/schemas/account/post.json
        example: !include v1/examples/account/post.json
    responses:
      201:
        body:
          application/json:
            schema: !include v1/schemas/account/one.json
            example: !include v1/examples/account/one.json
  patch:
    is: [ secured ]
    description: |
      User account update.
    body:
      application/json:
        schema: !include v1/schemas/users/patch.json
        example: !include v1/examples/users/patch.json
    responses:
      200:
        body:
          application/json:
            schema: !include v1/schemas/users/one.json
            example: !include v1/examples/users/one.json
  /reset-password:
    post:
      is: [ secured ]
      description: |
        User password reset.
      responses:
        200:
